language:
- node_js
node_js:
- '0.10'
env:
- ON_TRAVIS=true
branches:
  only:
  - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
- npm install
script:
- npm run test:ci
after_success:
- npm run coveralls
